[project]
name = "mangabuffcardscrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "selenium>=4.35.0",
    "selenium-stealth>=1.0.6",
]
